/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jaje.JAJE_library;

import jaje.JAJE_library.FileTool.FileListing;

public class Library {

    public static final String VERSION = "0.0.1";
    
    
    public static void main(String args[]){
        FileListing fList = new FileListing();
        String [] app = fList.getAllSistemApp();
        for(String p : app){
            System.out.println(p);
        }
        System.out.println("----"+app.length+"-----");
    }
}
